baseURL = "https://vr-mox.github.io/"
languageCode = "en-us"
title = "MOX: Multiplayer Online eXchange"
theme = "dimension"
publishDir = "docs"
unsafe= true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
